### ISSUE TITLE
Compatibility with Python 3.7

### ISSUE THREAD

**Issue by hilman-dayo** [gilbertfrancois/video-capture-async#2]
First of all, thank you for the code. It is really helpful.

However, running this program with Python 3.7 resulting this error:

    File "test/videocaptureasync.py", line 13
      def _run(self, n_frames=500, width=1280, height=720, async=False):
                                                             ^
     SyntaxError: invalid syntax

I believe this is because `async` is now a proper keyword in Python 3.7.
It will be really great if this code is updated for Python 3.7 too (maybe change `async` to `async_`).

**Comment by gilbertfrancois** [comment]
I fixed it, thank you!
